version: '3.8'

services:
  backend:
    build: ./docker/backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15
    volumes:
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"